# 1. The Database Connection URL
spring.datasource.url=jdbc:h2:mem:moviedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Tell Hibernate to auto-create our SQL tables based on our Java Models
spring.jpa.hibernate.ddl-auto=update

# 3. Print the hidden SQL code to the terminal so we can see the magic!
spring.jpa.show-sql=true